deps: enable secp256k1 in tendermint-rs
note that to make cargo deps, which complained about:

```
error: failed to select a version for `signature`
```

it was needed to run `cargo update -p signature` to:

```
Updating signature v1.5.0 -> v1.4.0
```