wasm: add tx_prelude and vp_prelude
We need to separate the tx and VP preludes into crates, because we
cannot declare a macro with the same name in one crate (fails with
error[E0428]: the name `debug_log` is defined multiple times).